services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knownet-api
    env_file: .env.production
    restart: always
    networks:
      - knownet

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
    container_name: knownet-client
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
    restart: always
    networks:
      - knownet

networks:
  knownet:
    driver: bridge
