services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knownet-api
    env_file: .env.production
    restart: always
    networks:
      - knownet

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: knownet-client
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
    networks:
      - knownet

networks:
  knownet:
    driver: bridge
