services:
  api:
    image: ghcr.io/barab2002/knownet-api:latest
    container_name: knownet-api
    env_file: .env.production
    network_mode: host
    restart: always

  client:
    image: ghcr.io/barab2002/knownet-client:latest
    container_name: knownet-client
    network_mode: host
    depends_on:
      - api
    restart: always
